### ISSUE TITLE
Errors occur while converting origin data to NumPy data file

### ISSUE THREAD

**Issue by JinChengneng** [wangshusen/PyRLA#1]
Errors occur when I try to run this command ```python processLibSVMData.py```.
The error is 
```
Traceback (most recent call last):
  File ".\processLibSVMData.py", line 48, in <module>
    processLibSVMData(inputFileName, d)
  File ".\processLibSVMData.py", line 27, in processLibSVMData
    mat[i, :] = parseRawData(rawData, d)
  File ".\processLibSVMData.py", line 14, in parseRawData
    vecIdxVal = list(map(parseRawDataUtil, vecStr))
  File ".\processLibSVMData.py", line 7, in parseRawDataUtil
    return [int(idxValPair[0]), float(idxValPair[1])]
ValueError: invalid literal for int() with base 10: '49.94356'
```
It seems that this is due to the direct type conversion from String to int, so I rewrite the function in the following way:
```
def parseRawDataUtil(idxValStr):
    idxValPair = idxValStr[2:-1].split(':') ###
    #idxValPair = idxValStr.split(':') ###
    return [int(float(idxValPair[0])), float(idxValPair[1])]
```
However, there's another error occurred, saying that 
```
Traceback (most recent call last):
  File ".\processLibSVMData.py", line 48, in <module>
    processLibSVMData(inputFileName, d)
  File ".\processLibSVMData.py", line 27, in processLibSVMData
    mat[i, :] = parseRawData(rawData, d)
  File ".\processLibSVMData.py", line 14, in parseRawData
    vecIdxVal = list(map(parseRawDataUtil, vecStr))
  File ".\processLibSVMData.py", line 7, in parseRawDataUtil
    return [int(float(idxValPair[0])), float(idxValPair[1])]
IndexError: list index out of range
```
I would appreciate it if you could take a glance at your code and fix it if possible. Best Regards.

**Comment by JinChengneng** [comment]
I have successfully run the code after replacing the first line with the commented code in function ```parseRawDataUtil(idxValStr)```, that is, 
```
def parseRawDataUtil(idxValStr):
    # idxValPair = idxValStr[2:-1].split(':') ###
    idxValPair = idxValStr.split(':') ###
    return [int(idxValPair[0]), float(idxValPair[1])]
```

BTW, it would be better if you remind guys who want to run the codes to create a folder named ```output``` in the root folder, otherwise, some errors may occur.
